### ISSUE TITLE
Questions about data migration

### ISSUE THREAD

**Issue by brianrak** [dlmelendez/identityazuretable#83] opened 2021-10-12 23:40 UTC
Hello, Dave. Thanks for the hard work on this project.

I have a question about data migration. The page that discusses migration (https://dlmelendez.github.io/identityazuretable/#/migration) seems to indicate that data migration is only necessary when upgrading from versions earlier than 2.2. I recently upgraded from 2.2.1 to 5.1, and so I understood that to mean that I didn't need to run migration.

However, when I pushed version 5.1 to production, I got exceptions in 5.1 when calling UserManager.GetUsersInRoleAsync. These exceptions happened only with my production data, not with any of my test databases, suggesting that there was a problem with the data. So I started looking into whether I needed to do a data migration. The data migration tool reported that I do indeed need to upgrade my users and roles. That was surprising to me, since I know I did this when I migrated from lower than 2.2 up to 2.2.1, so I first wanted to confirm: **Is this expected? Is the documentation just out of date?**

I found that the exceptions I mentioned above went away when I went back to Identity.AzureTable 5.0, so I have done that in production to get everything back to a working state. But this leads me to another question. Assuming that I do need to run data migration, **can I safely run the current version of the migration tool (5.1) on my data while using Identity.AzureTable 5.0 code?**

Thank you in advance for your help.

**Comment by brianrak** [comment] 2021-10-13 02:18
Update: I investigated this a little more and I think there is a bug here. I'll open a new issue.

**Comment by dlmelendez** [comment] 2022-02-05 19:37
Duplicate of #84

**Closed by dlmelendez** 2022-02-05 19:37 UTC
