### ISSUE TITLE
Claim Key Deletion Error

### ISSUE THREAD

**Issue by rgathub** [dlmelendez/identityazuretable#20] opened 2017-06-21 12:46 UTC
I am storing access token from an oAuth transaction in claims, when I add the claim it works fine but when I try to delete the claim, the azure table sends a 400 bad request every time. 

After troubleshooting for a while, I removed the claim value from the rowkey and generated new keys with only using the claimType. Now it is working fine. UriEncodeKeyHelper.cs --> Line: 63. 

I was wondering why are you using the claim value in the row key and if i should merge my changes or is there a better way to handle this.

Thanks
Rahul Gupta

**Comment by dlmelendez** [comment] 2017-06-21 22:02
@rgathub Just curious which package (aspnet or aspnetcore) are you using and what version? Could you attach a sample of what the claim value that reproduces the error? 
Thanks,
Dave

**Comment by rgathub** [comment] 2017-06-22 11:28
@dlmelendez  I am using the aspnet package and the latest code. (Key Version 1.66)

Sample Claim Value: EAABdGMzTwv8BALkEPOvXXRz3LNo6l77ymX75OO3gzadoxYLOs7KrMBi2zdjqULQ2CJAGUgwwsEGRFo2XIp0JPvoJEvaQdXgXZB1UzX8plkawZAdC93btP6lZBHettE0kfB91RODbWaj1aJbr3ejytBKq7vyP4mWq8lA9DWzCgZDZD

**Comment by dlmelendez** [comment] 2017-06-23 17:13
@rgathub Thanks for the repro info and I was able to confirm the issue. Looks like the rowkey is exceeding the maximum size. 
I guess I never answered your original question: the claim value is part of the key because the api supports multiple claim values for the same claim type. The claim value is an important part of the key in the remove operation. 
It looks like I need to revisit the claim key creation for a 1.7 release. I will get the logic updated with a migration path for old data since we are changing the claim key processing.
Thanks so much for reporting this bug. I hope to get a fix out soon.
-Dave

**Comment by rgathub** [comment] 2017-06-24 14:50
@dlmelendez  Thanks :) . Please let me know if I can be of any help.

**Comment by dlmelendez** [comment] 2017-08-28 19:23
Fixed in release 1.7. Data migration needed.

**Closed by dlmelendez** 2017-08-28 19:23 UTC
Labels: bug

**Comment by rgathub** [comment] 2017-08-29 13:14
Thanks @dlmelendez
