### ISSUE TITLE
StorageException when registering user

### ISSUE THREAD

**Issue by rocifier** [dlmelendez/identityazuretable#7] opened 2016-09-29 09:50 UTC
When I register a user in the .net core sample website (the tables are newly created), I get this exception thrown every time:

```
"An item with the same key has already been added. Key: UserName"
```

at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\n   at ElCamino.AspNetCore.Identity.AzureTable.UserStore`7.<CreateAsync>d__10.MoveNext() in /Users/ryanoconnor/Documents/fluid-cms/ElCamino.AspNetCore.Identity.AzureTable/UserStoreV2.partial.cs:line 248"

As you can see I've put the package into my project to debug it (the project is simply the dotnet core sample template with identity), line 248 is throwing the exception. I have tried to debug this but I don't understand why there is a collision. My UserName is my email address and I have checked in Storage Explorer and there are no rows inserted into the users table (the error is with the users table, not the index table - which populates fine despite the exception).

Any ideas? Any more info I can provide?

**Comment by dlmelendez** [comment] 2016-09-29 14:30
This caused by a bug in the storage library https://github.com/Azure/azure-storage-net/issues/341 . The fix is to use version "WindowsAzure.Storage": "7.1.3-preview" as this bug was introduced after this release. The storage library team says the fix is slated for v8.

**Comment by rocifier** [comment] 2016-09-30 07:24
Thank you so much! That worked. Ah, preview libraries...

**Comment by dlmelendez** [comment] 2016-10-23 03:19
Update: Looks like this is slated for CY 16 for storage 8.0 release to be fixed in the storage library. https://github.com/Azure/azure-storage-net/issues/341

**Comment by dlmelendez** [comment] 2016-12-23 01:31
https://github.com/dlmelendez/identityazuretable/releases/tag/v1.6.5

**Closed by dlmelendez** 2016-12-23 01:31 UTC
Labels: bug
