### ISSUE TITLE
Claims Support for IdentityUserV2

### ISSUE THREAD

**Issue by tbasallo** [dlmelendez/identityazuretable#48] opened 2019-09-02 19:16 UTC
The latest release has an obsolete warning on IdentityUser and recommends the move to V2. However, V2 does not support claims (or roles).

Is there guidance on using V2 with claims or is there a different plan all together for claims?

**Comment by dlmelendez** [comment] 2019-09-09 16:56
@tbasallo please check out issue #46 for the response.
Duplicate of 46#

**Closed** 2019-09-10 15:16 UTC
